name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'raysan5/raylib'
        version: 'tags/4.2.0'
        regex: true
        file: "raylib-4.2.0_linux_amd64.tar.gz"
        target: 'lib/raylib.tar.gz'
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    #- name: configure
      #run: ./configure
    - name: compilation check
      run: make -C updated/ pipeline
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
